# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - main

jobs:
  test-funnel:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: kHWdT49ud511CNTRL # <<<--- add you tailscale creds to your gh secrets
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci                                        	# <<<--- THIS IS IMPORTANT

      - name: ping                                           	# <<<--- LETS PING A SERVER FOR TESTING
        run: |
          curl +X https://dcworkshop1.tailbf22ca.ts.net/

