# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - main

jobs:
  test-funnel:
    runs-on: ubuntu-latest
    steps:
      - name: Test Tailscale Funnel
        run: |
           ping -c 5 100.85.222.43
           curl -X GET           https://100.85.222.43

